<?PHP
?>
<html>
	<head>
			<link rel="stylesheet" type="text/css" href="./style/touch.css">
	</head>
	<body>
		<h1>Qui sommes-nous?</h1>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer in dictum odio. Praesent rhoncus pretium nisl, sit amet laoreet urna luctus at. Etiam id nisi sapien. Pellentesque eleifend aliquam lacus, commodo commodo turpis ultricies vel. Quisque tempor rutrum erat at varius. Sed et convallis nunc. Duis in nisi sit amet leo mattis volutpat. In hac habitasse platea dictumst.
		
		Vivamus consectetur, nulla vulputate bibendum pellentesque, dolor dolor porta augue, vitae iaculis massa nunc et tortor. Praesent mauris neque, maximus ut finibus a, efficitur nec eros. Aenean pellentesque laoreet nibh a hendrerit. Pellentesque dictum, nibh quis sodales facilisis, ligula neque pellentesque tortor, in vestibulum velit neque sit amet ipsum. Curabitur convallis viverra dolor a pretium. Donec vitae tempus libero. Integer malesuada lacus vitae orci vestibulum pretium. Fusce viverra lectus risus, vitae commodo magna ullamcorper nec. Sed eu arcu metus. Nunc et scelerisque massa. Aliquam pellentesque elit nec rutrum suscipit. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
		
		Nunc a sem varius, faucibus ipsum non, vestibulum ipsum. Nam sagittis dui a faucibus auctor. Morbi interdum est ut augue consectetur efficitur. Integer dapibus est augue, vitae cursus risus sollicitudin sit amet. Proin sed eros sollicitudin, efficitur sapien auctor, lobortis metus. Proin et felis et risus gravida lacinia. Integer tempor quis lacus ut auctor. Mauris sodales velit id diam vulputate scelerisque. Proin id turpis velit. Suspendisse sed tristique diam, nec semper mi. Integer a dui condimentum, auctor purus nec, tincidunt dolor. Maecenas euismod a ipsum vitae sollicitudin. Nulla in sodales dui. Etiam sed urna vel tellus placerat porta sit amet vitae diam. Morbi rhoncus, turpis sit amet finibus interdum, purus erat pellentesque ex, vitae malesuada tellus neque nec neque.
		
		Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas convallis ornare cursus. Quisque ultrices, justo quis molestie malesuada, ante purus lobortis mauris, ac blandit nibh justo vitae lectus. Donec enim diam, facilisis id dui at, congue finibus turpis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse ac mauris a quam tincidunt lacinia. Phasellus et purus sit amet magna interdum malesuada vitae sit amet nibh. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras et risus elit. Nulla in ex elementum, ullamcorper lectus a, facilisis risus. Suspendisse eu ultrices mi. In quis feugiat nulla, at imperdiet lacus. Duis nec orci hendrerit, molestie neque non, mattis eros. Vivamus lacinia tincidunt urna, a gravida lorem convallis a.
		
		Nunc erat lectus, dictum eget rutrum et, malesuada at arcu. Nullam hendrerit viverra leo vitae vestibulum. Vestibulum lobortis urna quis ex consectetur interdum congue vitae lorem. Sed ac turpis sem. In rutrum elit vulputate pretium semper. Curabitur maximus risus id purus tincidunt molestie. Fusce et ornare nibh. Pellentesque commodo, augue tincidunt varius volutpat, lacus ipsum malesuada est, in convallis mauris diam vitae felis. Ut malesuada iaculis arcu, vel commodo mauris rhoncus in. Mauris congue, sapien laoreet aliquet porta, mauris enim luctus nisl, vitae dictum nulla enim iaculis urna. Morbi tempor blandit diam, eu vestibulum sem mattis id.
		
		In molestie dui sem, nec lacinia nibh fermentum sed. Donec a tempor arcu. Mauris eu facilisis sapien, id consequat diam. Praesent eros sapien, placerat et lacus eget, eleifend tincidunt erat. Nunc euismod dui in mauris viverra, aliquam viverra dolor euismod. Suspendisse vestibulum posuere nulla. Vivamus turpis lorem, auctor in erat at, tempor fringilla dolor. Sed tempus, ante eu ornare pharetra, erat sem faucibus tortor, eu sodales elit libero sed nibh. Pellentesque viverra erat sem, vel porta magna pretium ac. Phasellus lacinia, dolor id lobortis consequat, urna odio vulputate nisi, at euismod orci velit vel ligula.
		
		In hac habitasse platea dictumst. Integer in libero volutpat, porta arcu eu, fermentum nibh. Aenean vel nulla vel dolor rutrum convallis. In porttitor rhoncus risus. Nulla accumsan ultricies orci nec sagittis. Nam cursus neque a arcu suscipit, quis sagittis nisl tristique. Donec eu pulvinar risus. Phasellus viverra velit non urna consectetur semper.
		
		Vestibulum eu sodales ex. Curabitur fringilla sodales arcu in consectetur. Nulla nulla sapien, sollicitudin a faucibus vel, volutpat vel mi. Aenean sollicitudin, dolor non luctus cursus, lorem lacus interdum justo, eu feugiat ante felis ut lectus. Aliquam tellus velit, pretium vitae sodales sed, aliquet vel nunc. Cras in ligula ac elit tempus pulvinar eu vitae nisi. Vivamus aliquam non metus a molestie. Duis elementum massa quis pretium suscipit. Aenean ipsum libero, iaculis sit amet nisl in, fermentum blandit turpis.
		
		Pellentesque feugiat semper augue quis hendrerit. Proin non nisl ut elit rutrum porta. Pellentesque nec lacus vitae ligula dignissim tristique eget at lectus. Cras mattis libero et est dignissim fringilla. Maecenas dapibus, libero quis blandit vehicula, leo enim lobortis tortor, vel commodo lacus magna sed arcu. Curabitur nec molestie dui. Donec libero leo, consectetur fringilla ipsum eget, gravida suscipit enim. Fusce semper, nibh sit amet pulvinar venenatis, elit justo finibus dolor, quis ultrices ex risus ac leo. Quisque neque nibh, finibus quis posuere a, gravida eu nibh. In hac habitasse platea dictumst. Morbi ut semper dui. Phasellus in elit vel lorem ullamcorper consectetur dapibus at leo. Suspendisse ac mi eu mi suscipit lacinia vel et arcu.
		
		Proin non elit dapibus, finibus quam a, cursus risus. Donec placerat felis vel congue bibendum. Nulla viverra risus felis, id ornare neque euismod at. Fusce a lorem orci. Vestibulum facilisis nunc ut dolor tincidunt consectetur. Integer nec commodo urna. Maecenas nec lacus sit amet lectus aliquet consectetur eu vitae augue. Integer eleifend venenatis nunc, sed tempor arcu. Sed sit amet pulvinar nibh. Quisque ultricies rhoncus enim a viverra. Aliquam vitae nisi arcu. Vivamus venenatis vel dui nec ultrices. Quisque blandit leo non magna tincidunt, id commodo justo efficitur. Vestibulum posuere dolor ac felis blandit mollis.
		<br />
		<br />
		<a href='index.php'><span class='btn'>Accueil</span><a />
	</body>
</html>